/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package infoextraction.InfoExtract.unstrcturedInfo.revisedcrf;

import infoextraction.InfoExtract.unstrcturedInfo.filters.CrfFilteredFeature;
import infoextraction.InfoExtract.unstrcturedInfo.utilities.TaggedToken;
import java.util.List;
import java.util.Set;

/**
 *
 * @author Kaihua Liu
 */
public abstract class CrfFeatureGenerator<K, G> {

    public CrfFeatureGenerator(Iterable<? extends List<? extends TaggedToken<K, G>>> corpus, Set<String> tags) {
        super();
        this.corpus = corpus;
        this.tags = tags;
    }

    /**
     * Generate the features (to be lated retrieved by {@link #getFeatures()}).
     */
    public abstract void generateFeatures();

    /**
     * Return the set of features earlier generated by
     * {@link #generateFeatures()}.
     *
     * @return the set of features earlier generated by
     * {@link #generateFeatures()}.
     */
    public abstract Set<CrfFilteredFeature<K, G>> getFeatures();

    protected final Iterable<? extends List<? extends TaggedToken<K, G>>> corpus;
    protected final Set<String> tags;
}
